defaults:
  run:
    shell: bash
    working-directory: scripts
on:
  workflow_call:
  push:
    branches:
    - main
    - feature_*
jobs:
  test-job:
    runs-on: self-hosted
    steps: 
      - name: run test script
        run: testScript.sh
