## do not touch anything after this
defaults:
  run:
    shell: bash
#    working-directory: /scripts/sample-script
on:
  workflow_call:
  push:
    branches:
      - main
      - feature_*
jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          clean: false
      - name: run test script
        #uses: ./scripts/sample-script
        run: |
          echo $(ls)
          cd ./scripts/sample-script
          bash runTests.sh
        # bash run-tests.sh [pass in the test_directory argument]
