defaults:
  run:
    shell: bash
#    working-directory: /scripts/sample-script
on:
  workflow_call:
  push:
    branches:
    - main
    - feature_*
jobs:
  test-job:
    runs-on: self-hosted
    with: 
      path: ./scripts/sample-script
    steps: 
      - name: run test script
        run: testScript.sh
