on:
  workflow_call:
  push:
    branches:
    - main
    - feature_*
jobs:
  test-job:
    runs-on: self-hosted
    steps: 
      - name: run test script
        run: ./scripts/sample-script/testScript.sh
        shell: bash
