## Users need to fill out these config variables
config:
  test_directory: /Users/jaymiee/Desktop/json/


## do not touch anything after this
defaults:
  run:
    shell: bash
#    working-directory: /scripts/sample-script
on:
  workflow_call:
  push:
    branches:
      - main
      - feature_*
jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: run test script
        #uses: ./scripts/sample-script
        run: |
          echo $(ls)
          cd ./scripts/sample-script
          bash testScript.sh 
        # bash run-tests.sh [pass in the test_directory argument]