on:
  workflow_call:
  push:
    branches:
    - main
    - feature_*
jobs:
  test-job:
    runs-on: self-hosted
    steps: 
      - name: run test script
        run: ls > test_wf.txt
      - name: view file
        run: cat test_wf.txt
